### ISSUE TITLE
Can't get connection

### ISSUE THREAD

**Issue by LunaMeadows** [TheStaticTurtle/pyVBAN#1]
I was able to troubleshoot the code to the point of getting verbose=true to output to console, however no sound is being transmitted.

**Comment by TheStaticTurtle** [comment]
Would you be able to post your code?
This lib is really old I'm not sure if it still works I'll have to look into it

**Comment by LunaMeadows** [comment]
I just used the sample code that was given. All I changed in pyVBAN was remove ord() and fix the print strings for python3.

**Comment by TheStaticTurtle** [comment]
Humm long time since I looked at the code but I believe that the ord should stay there, was there on error when you had them

**Comment by LunaMeadows** [comment]
Sorry for the late reply, “TypeError: ord() expected string of length 1, but int found” was the error I was getting and from what I saw, python3 was not needed anymore but may of been looking at it wrong.

**Comment by wolf3x** [comment]
Hi, i  have the same problem as LunaMeadows, it will be great if you can look at the code, it will be a great help for my audio setup

**Comment by TheStaticTurtle** [comment]
By any chance, are you using python3 ?

**Comment by TheStaticTurtle** [comment]
If yes, please pull the latest version, I've updated it for python 3.
My bad that I haven't written it anywhere, but it was written for py2, these errors are typical of a py2 script started with py3. It would have been a good idea to test it on py2 since it was first written 2 years ago (I realize that py2 hit his EOL this is why I updated)

Could you verify that everything is working now ?

**Comment by LunaMeadows** [comment]
I pulled the new code however I am still getting errors, however they are new errors. 

When running
`import pyVBAN
cl = pyVBAN.VBAN_Recv("127.0.0.1","Stream7",6980,7,verbose=True)
cl.runforever()`

I get 
`Traceback (most recent call last):
  File "C:/Users/derri/Documents/Projects/AudioTransmiter/test.py", line 4, in <module>
    cl = pyVBAN.VBAN_Recv("127.0.0.1","Stream7",6981,10,verbose=True)
  File "C:\Users\derri\Documents\Projects\AudioTransmiter\pyVBAN.py", line 27, in __init__
    self.stream = self.p.open(format = self.p.get_format_from_width(2), channels = self.channels, rate = self.sampRate, output = True, output_device_index=self.outDeviceIndex)
  File "C:\Users\derri\AppData\Local\Programs\Python\Python38\lib\site-packages\pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\derri\AppData\Local\Programs\Python\Python38\lib\site-packages\pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels`

**Comment by TheStaticTurtle** [comment]
What is the number of channel that input card that you are using have? mono, stereo or more ?

+Could you give me the output of: (replace inDeviceIndex with your index)
```py
import pyaudio
p = pyaudio.PyAudio()
p.get_device_info_by_host_api_device_index(0, inDeviceIndex).get('maxInputChannels')
```

**Comment by LunaMeadows** [comment]
So that is completely my fault. I chose the input id instead of the output id. Works great now.

**Comment by TheStaticTurtle** [comment]
Glad to know it works now.
@wolf3x I'm closing this issue if you still have a problem please open a new issue
