### ISSUE TITLE
Multiple send stream and send + recv not working

### ISSUE THREAD

**Issue by ACorentin** [TheStaticTurtle/pyVBAN#4]
Hello,

I failed to send multiple streams, either to two separate devices or to one, even with different ports.
I then tried with Python Process but the result is the same.
I also cannot use send and receive at the same time.
Here is my code:

```
import pyVBAN
from multiprocessing import Process

def send(ip, port, streamName, sampleRate, deviceId):
    vbanSendSlot = pyVBAN.VBAN_Send(ip, port, streamName, sampleRate, deviceId, verbose=False)
    vbanSendSlot.runforever()

def recv(ip, port, streamName, deviceId):
    vbanRecvSlot = pyVBAN.VBAN_Recv(ip, streamName, port, deviceId, verbose=True)
    vbanRecvSlot.runforever()

def startSend1():
    sendSlot1 = Process(target=send, args=("10.0.254.6", 6980, "Stream1", 48000, 12))
    sendSlot1.start()
    sendSlot1.join()

def startSend2():
    sendSlot2 = Process(target=send, args=("10.0.254.6", 6981, "Stream2", 44100, 12))
    sendSlot2.start()
    sendSlot2.join()

def startRecv1():
    recvSlot1 = Process(target=recv, args=("10.0.254.6", 6980, "RECV", 14))
    recvSlot1.start()
    recvSlot1.join()


if __name__ == '__main__':
    startSend1()
    startSend2()
    startRecv1()
```

Is this normal or is there a specific setting to be made?

Sorry if my English is not very good, I use Google Translate.

**Comment by TheStaticTurtle** [comment]
Is there a specific error?
Does it work with only one stream?
For testing does it work if you run in two different scripts instead of using Process?

**Comment by ACorentin** [comment]
No error is displayed
It works with a single stream in reception or transmission
Yes it works with two separate scripts, as well for two sending flows as for one sending and one receiving

**Comment by TheStaticTurtle** [comment]
Could you try using a while where you would call the run once function of every stream and remove the multiprocessing completely?

**Comment by ACorentin** [comment]
It works, however, I hear cracklings on the receiver, they are followed by the error "[Errno -9988] Stream closed" in the console

My code : 
```
import pyVBAN

def send(ip, port, streamName, sampleRate, deviceId):
    vbanSendSlot = pyVBAN.VBAN_Send(ip, port, streamName, sampleRate, deviceId, verbose=False)
    return vbanSendSlot


def recv(ip, port, streamName, deviceId):
    vbanRecvSlot = pyVBAN.VBAN_Recv(ip, streamName, port, deviceId, verbose=False)
    return vbanRecvSlot

sendSlot1 = send("10.0.254.6", 6980, "Stream1", 44100, 12)
sendSlot2 = send("10.0.10.9", 6980, "Stream1", 44100, 12)
recvSlot1 = recv("10.0.254.6", 6980, "RECV", 14)

while True:
    sendSlot1.runonce()
    sendSlot2.runonce()
    recvSlot1.runonce()
```

**Comment by ACorentin** [comment]
Perhaps a speed problem?
The different devices are on the same 5Ghz WiFi network (With a different router than the operator box )

**Comment by TheStaticTurtle** [comment]
Seems to be a pyAudio issue unfortunately I'm no expert at this 😅 
I noticed that you are using the same input twice could you try commenting one of the two?

**Comment by ACorentin** [comment]
Sorry, I thought it was "pyVBAN" throwing this error. I have tried using two different inputs but the error also occurs.
However, the latter is very random, which makes it difficult to locate the problem.
What is certain is that it did not happen when testing a single stream with "runforever", or when testing multiple streams in separate scripts.

**Comment by ACorentin** [comment]
The error does not produce when there is only one stream in transmission, even if there is another in reception (using "runonce" in the loop)
So it really looks like a problem with access to audio devices by pyAudio
