### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by engineerjoe440** [TheStaticTurtle/pyVBAN#7]
I was curious if you had preferences on the license for this project? Others in the same space have seemed to have gone with either the GPL 3.0 or Apache 2.0, and I was wondering if you had any thoughts on this?

**Comment by TheStaticTurtle** [comment]
Hi, this is a **very** old project of mine at a time when I wasn't concerned about licence.
This project is a very niche tool that would only really be used for tinkering (imo) hence the GPLv3.
