### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by cardil** [TheStaticTurtle/pyVBAN#9]
I'm using this project to transmit my mic (via pipewire) to my remote gaming rig (running Voicemeeter Banana on Windows). It works well, thx @TheStaticTurtle!

I would like to have some tooling based on this library, maybe with some GUI, but your code isn't available on [PyPI](https://pypi.org). This hinders the ease of use, as I need to either fork, or bundle your code somehow. I rather just use it as a regular PyPI dependency.

Would you mind publishing it on [PyPI](https://pypi.org)?

**Comment by TheStaticTurtle** [comment]
Hi, 

I have considered it before but I am not happy with the current state of the code and doesn't implement the full spec (https://vb-audio.com/Voicemeeter/VBANProtocol_Specifications.pdf)

I need a break from my other projects, so I'll see what I can do to re-write it properly

**Comment by TheStaticTurtle** [comment]
Hi,

I did a big refractor, the API is mostly the same (see README). However, it would be good if you could test it!
If everything checks out, I'll publish it on PyPI tomorrow.

Samuel

**Comment by cardil** [comment]
Thanks. I'll test it soon.

**Comment by cardil** [comment]
The listing of devices and sending the sound works. I ran:

```python
import logging
import pyvban

logging.basicConfig(level=logging.DEBUG)

pyvban.utils.device_list()

sender = pyvban.utils.VBAN_Sender(
    receiver_ip="192.168.5.6",
    receiver_port=6980,
    stream_name="ksuszyns",
    sample_rate=48000,
    channels=2,
    device_index=12
)
sender.run()
```
The log was:

```log
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
INFO:device_list:Input:
INFO:device_list:	0 - Razer Kiyo: USB Audio (hw:0,0)
INFO:device_list:	1 - Realtek USB2.0 Audio: Audio (hw:1,0)
INFO:device_list:	2 - ThinkPad Thunderbolt 4 Dock USB: Audio (hw:2,0)
INFO:device_list:	3 - sof-hda-dsp: - (hw:3,0)
INFO:device_list:	7 - sof-hda-dsp: - (hw:3,6)
INFO:device_list:	8 - sof-hda-dsp: - (hw:3,7)
INFO:device_list:	10 - sysdefault
INFO:device_list:	11 - spdif
INFO:device_list:	12 - pipewire
INFO:device_list:	13 - default
INFO:device_list:Output:
INFO:device_list:	3 - sof-hda-dsp: - (hw:3,0)
INFO:device_list:	4 - sof-hda-dsp: - (hw:3,3)
INFO:device_list:	5 - sof-hda-dsp: - (hw:3,4)
INFO:device_list:	6 - sof-hda-dsp: - (hw:3,5)
INFO:device_list:	9 - sof-hda-dsp: - (hw:3,31)
INFO:device_list:	12 - pipewire
INFO:device_list:	13 - default
INFO:VBAN_Sender_192.168.5.6:6980_ksuszyns:Hellow world
```

I was able to record the input device on the remote machine.

**Comment by TheStaticTurtle** [comment]
So send works for you ?
Could you try receive and text ?

**Comment by cardil** [comment]
> @TheStaticTurtle: So send works for you ?

Yes.

> @TheStaticTurtle: Could you try receive and text?

I don't know how I may test the receive and text functions. Sorry.

**Comment by TheStaticTurtle** [comment]
Ok nice,

I'll do some testing later today, maybe improve the errors a bit, and then I'll publish the package.
I'm much happier with this code than the crap that I wrote 5 years ago, but there's always room for improvement.

I'll notify this issue once I publish it

Thanks,
Samuel

**Comment by TheStaticTurtle** [comment]
Done: https://pypi.org/project/pyVBAN/
